//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 10:13:22 AM EDT 
//


package chartml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Groups" type="{}DataGroupsType" minOccurs="0"/>
 *         &lt;element name="Variables" type="{}VariableGroupType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataType", propOrder = {
    "groups",
    "variables"
})
public class DataType {

    @XmlElement(name = "Groups")
    protected DataGroupsType groups;
    @XmlElement(name = "Variables")
    protected VariableGroupType variables;

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link DataGroupsType }
     *     
     */
    public DataGroupsType getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataGroupsType }
     *     
     */
    public void setGroups(DataGroupsType value) {
        this.groups = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link VariableGroupType }
     *     
     */
    public VariableGroupType getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableGroupType }
     *     
     */
    public void setVariables(VariableGroupType value) {
        this.variables = value;
    }

}
