//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 10:13:22 AM EDT 
//


package chartml.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the chartml.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Chart_QNAME = new QName("", "Chart");
    private final static QName _String_QNAME = new QName("", "string");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: chartml.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GlobalRenderingType }
     * 
     */
    public GlobalRenderingType createGlobalRenderingType() {
        return new GlobalRenderingType();
    }

    /**
     * Create an instance of {@link DataPointType }
     * 
     */
    public DataPointType createDataPointType() {
        return new DataPointType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link ChartType }
     * 
     */
    public ChartType createChartType() {
        return new ChartType();
    }

    /**
     * Create an instance of {@link DataGroupsType }
     * 
     */
    public DataGroupsType createDataGroupsType() {
        return new DataGroupsType();
    }

    /**
     * Create an instance of {@link VariableType }
     * 
     */
    public VariableType createVariableType() {
        return new VariableType();
    }

    /**
     * Create an instance of {@link DataGroupType }
     * 
     */
    public DataGroupType createDataGroupType() {
        return new DataGroupType();
    }

    /**
     * Create an instance of {@link PointPartType }
     * 
     */
    public PointPartType createPointPartType() {
        return new PointPartType();
    }

    /**
     * Create an instance of {@link VariableRenderingType }
     * 
     */
    public VariableRenderingType createVariableRenderingType() {
        return new VariableRenderingType();
    }

    /**
     * Create an instance of {@link RenderingType }
     * 
     */
    public RenderingType createRenderingType() {
        return new RenderingType();
    }

    /**
     * Create an instance of {@link DataRenderingType }
     * 
     */
    public DataRenderingType createDataRenderingType() {
        return new DataRenderingType();
    }

    /**
     * Create an instance of {@link VariableGroupType }
     * 
     */
    public VariableGroupType createVariableGroupType() {
        return new VariableGroupType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChartType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Chart")
    public JAXBElement<ChartType> createChart(ChartType value) {
        return new JAXBElement<ChartType>(_Chart_QNAME, ChartType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

}
