//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 10:13:22 AM EDT 
//


package chartml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RenderingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RenderingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GlobalRendering" type="{}GlobalRenderingType" minOccurs="0"/>
 *         &lt;element name="DataRendering" type="{}DataRenderingType" minOccurs="0"/>
 *         &lt;element name="VariableRendering" type="{}VariableRenderingType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RenderingType", propOrder = {
    "globalRendering",
    "dataRendering",
    "variableRendering"
})
public class RenderingType {

    @XmlElement(name = "GlobalRendering")
    protected GlobalRenderingType globalRendering;
    @XmlElement(name = "DataRendering")
    protected DataRenderingType dataRendering;
    @XmlElement(name = "VariableRendering")
    protected VariableRenderingType variableRendering;

    /**
     * Gets the value of the globalRendering property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalRenderingType }
     *     
     */
    public GlobalRenderingType getGlobalRendering() {
        return globalRendering;
    }

    /**
     * Sets the value of the globalRendering property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalRenderingType }
     *     
     */
    public void setGlobalRendering(GlobalRenderingType value) {
        this.globalRendering = value;
    }

    /**
     * Gets the value of the dataRendering property.
     * 
     * @return
     *     possible object is
     *     {@link DataRenderingType }
     *     
     */
    public DataRenderingType getDataRendering() {
        return dataRendering;
    }

    /**
     * Sets the value of the dataRendering property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRenderingType }
     *     
     */
    public void setDataRendering(DataRenderingType value) {
        this.dataRendering = value;
    }

    /**
     * Gets the value of the variableRendering property.
     * 
     * @return
     *     possible object is
     *     {@link VariableRenderingType }
     *     
     */
    public VariableRenderingType getVariableRendering() {
        return variableRendering;
    }

    /**
     * Sets the value of the variableRendering property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableRenderingType }
     *     
     */
    public void setVariableRendering(VariableRenderingType value) {
        this.variableRendering = value;
    }

}
