//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 10:13:22 AM EDT 
//


package chartml.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VariableDataType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VariableDataType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Nominal"/>
 *     &lt;enumeration value="Ordinal"/>
 *     &lt;enumeration value="Interval"/>
 *     &lt;enumeration value="Ratio"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VariableDataType")
@XmlEnum
public enum VariableDataType {

    @XmlEnumValue("Nominal")
    NOMINAL("Nominal"),
    @XmlEnumValue("Ordinal")
    ORDINAL("Ordinal"),
    @XmlEnumValue("Interval")
    INTERVAL("Interval"),
    @XmlEnumValue("Ratio")
    RATIO("Ratio");
    private final String value;

    VariableDataType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VariableDataType fromValue(String v) {
        for (VariableDataType c: VariableDataType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
